### ISSUE TITLE
Adding Slack `app_manifest` to documentation

### ISSUE THREAD

**Issue by dteycheney** [nautobot/nautobot-plugin-chatops#96]
### Environment
* Nautobot version:  1.1.2
* nautobot-plugin-chatops version:  1.5.0

### Proposed Functionality

Slack has a Beta functionality to add an `app_manifest`, which if adopted by nautobot, could greatly simplify the documentation and setup:

https://github.com/nautobot/nautobot-plugin-chatops/blob/develop/docs/chat_setup/slack_setup.md

Slack Doco: https://api.slack.com/reference/manifests

Below is a rough example of the template file which could be provided to speed up the setup process:

```yaml
_metadata:
  major_version: 1
  minor_version: 1
display_information:
  name: Nautobot ChatOps
features:
  bot_user:
    display_name: Nautobot ChatOps
    always_online: false
  slash_commands:
    - command: /nautobot
      url: https://<nautobot_server>/api/plugins/chatops/slack/slash_command/
      description: Nautobot Utility Function
      should_escape: false
oauth_config:
  scopes:
    bot:
      - commands
      - chat:write
      - channels:read
      - files:write
      - incoming-webhook
      - users:read
      - app_mentions:read
      - im:read
      - groups:read
      - mpim:read
settings:
  interactivity:
    is_enabled: true
    request_url: https://<nautobot_server>/api/plugins/chatops/slack/interaction/
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false

```

### Use Case

Could be used to speed up the initial deployment of a Slack app or, ensure consistency is undertaken when deploying new apps.
